name: Build Rainy iOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4

    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer

    - name: Build Project for iPhone (Unsigned)
      run: xcodebuild clean build -scheme Rainy -destination "generic/platform=iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -derivedDataPath BuildData/

    - name: Package into IPA
      run: |
        mkdir -p Payload
        cp -r BuildData/Build/Products/Debug-iphoneos/Rainy.app Payload/
        zip -r Rainy.ipa Payload

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rainy-App
        path: Rainy.ipa
